sonar.projectKey=tyrpik_sonar-client
sonar.organization=tyrpik
sonar.projectName=sonar-client
sonar.projectVersion=1.0
sonar.sources=src
sonar.exclusions=**/*.test.tsx,**/*.test.ts,node_modules/**
sonar.tests=src
sonar.test.inclusions=**/*.test.tsx,**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info